#!/bin/bash

#Nod Banner
export COLUMNS
NODRED="\033[38;5;196m"
NODBG="\033[38;5;232m"
echo -e $NODRED --------------------------------------------------------------------
echo -e $NODBG MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMMMMMMMMMMMMM${NODRED}ZZZZZZZZZ${NODBG}MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMMMMMMMMMMMM${NODRED}ZZZZZZZZZZZ${NODBG}MMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMMMMMMMMMMM${NODRED}Z${NODBG}MMMMMMMMM${NODRED}ZZZ${NODBG}MMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMMMMMMMMMM${NODRED}Z${NODBG}MMMMMMMMMMMMM${NODRED}Z${NODBG}MMMMMMMMMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMMMMMMMMM${NODRED}Z${NODBG}MMMMMM${NODRED}ZZ${NODBG}MMMMMMM${NODRED}Z${NODBG}MMMMMMMMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMMMMMMMM${NODRED}ZZ${NODBG}MMM${NODRED}ZZZZZZZZ${NODBG}MMMMM${NODRED}Z${NODBG}MMMMMMMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMMMMMMM${NODRED}ZZ${NODBG}MMM${NODRED}ZZZZZZZZZZ${NODBG}MMMMM${NODRED}Z${NODBG}MMMMMMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMMMMMM${NODRED}ZZZ${NODBG}MMM${NODRED}ZZZZZZZZZZZZ${NODBG}MMM${NODRED}ZZ${NODBG}MMMMMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMMMMM${NODRED}ZZZZZ${NODBG}MMM${NODRED}ZZZZZZZZZZ${NODBG}MMMMM${NODRED}ZZ${NODBG}MMMMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMMMM${NODRED}ZZZZZZZZ${NODBG}M${NODRED}ZZZZZZZZZZ${NODBG}MMMMM${NODRED}ZZZ${NODBG}MMMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMNM${NODRED}ZZZZZZZZZ${NODBG}M${NODRED}ZZZZZZZZZZ${NODBG}MMMM${NODRED}ZZZZZ${NODBG}MMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMM${NODRED}ZZZZZZZZZZZZZZZZZZ${NODBG}MMMMMM8${NODRED}ZZZZZZ${NODBG}MMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMM${NODRED}ZZZZZZZZZZZZZZZZZ${NODBG}MMMMMMM${NODRED}ZZZZZZZ${NODBG}MMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMMM${NODRED}ZZZZZZZZZZZ${NODBG}MMMMMMMMMMM${NODRED}ZZZZZZZ${NODBG}MMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMMMM${NODRED}ZZZZZZZZ${NODBG}MMMMMMMMMMN${NODRED}ZZZZZZZZ${NODBG}MMMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMMMMM${NODRED}ZZZZZZZ${NODBG}MMMMMMMN${NODRED}ZZZZZZZZZZ${NODBG}MMMMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMMMMMM${NODRED}ZZZZZZZZZZZZZZZZZZZZZZZ${NODBG}MMMMMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMM
echo -e $NODBG MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo -e $NODRED --------------------------------------------------------------------
echo

##~/scripts/py_scripts/nod_col.py