#!/usr/bin/env bash

###############
# Configuration
###############

SVNHOOK_REPOS="$1"
SVNHOOK_TXN="$2"
SVNHOOK_SVNLOOK=/usr/bin/svnlook
SVNHOOK_LOGMSG="$($SVNHOOK_SVNLOOK log -t "$SVNHOOK_TXN" "$SVNHOOK_REPOS")"
SVNHOOK_REGEX="(([A-Za-z]+[\-]{1}[0-9]+)|[Tt][Ee][Cc][Hh])"
SVNHOOK_REVERTREGEX=".*([Rr]evert|[Rr]everting)(.*[\n]*.*)*"
SVNHOOK_MERGEREGEX=".*([Mm]erge|[Mm]erging)(.*[\n]*.*)*"

#######
# Flags
#######

svn_user_commit_strict="false"
svn_merge_strict="false"
svn_revert_strict="false"

##################
# Regex Assignment
##################

if [[ $svn_user_commit_strict == "true" ]]; then
	SVNHOOK_REGEX="([A-Za-z\-\/]+\s+[\-]\s+([A-Za-z]+[\-][0-9]*|[Tt][Ee][Cc][Hh])\s?[-:]+\s?.*)"
fi

if [[ $svn_merge_strict == "true" ]]; then
	SVNHOOK_MERGEREGEX=""
fi

#if [[ $svn_revert_strict == "true" ]]; then
#	#SVNHOOK_REVERTREGEX="(Revert)+.(\".*\")([.\n]*)+(.*commit.*\.)"
#fi

###########
# Functions
###########

#[TODO] Add strict/non-strict flag support here. Simple if statement after the case.
usage() {
	case "$1" in
		reg_commit)
			echo "Please Use The Format: Initials - Story-# - Message" >&2
			echo "For Example: AK - CSS-123 - Commit Message" >&2
			##echo "For No Story: AK - TECH - Commit Message" >&2
			;;
		null_string)
			echo "Please enter a commit message." >&2
			echo "For regular commits use the format: Initials - Story-# - Message" >&2
			echo "For Example: AK - CSS-123 - Commit Message" >&2
			;;
	esac

}

#######################
# Conditional Filtering
#######################

if [[ -z "$SVNHOOK_LOGMSG" ]]; then
	echo "No commit message found: \"${SVNHOOK_LOGMSG}\"" >&2
	usage "null_string"
	exit 1
fi

if [[ `grep -E $SVNHOOK_REVERTREGEX <<< "$SVNHOOK_LOGMSG"` ]]; then
	echo "[Revert] Revert Found" >&2
	usage
	exit 0
fi

if [[ `grep -E $SVNHOOK_MERGEREGEX <<< "$SVNHOOK_LOGMSG"` ]]; then
	echo "[Merge] Merge Found" >&2
	usage
	exit 0
fi

if [[ ! `grep -E $SVNHOOK_REGEX <<< "$SVNHOOK_LOGMSG"` ]]; then
	echo "Invalid usage in svn commit message: \"${SVNHOOK_LOGMSG}\"" >&2
	usage "reg_commit"
	exit 1
fi